### PR TITLE
Disable BLAS by default

### PR DESCRIPTION
**Pull request by jschueller**
Enabling BLAS makes cminpack crash because integer arguments are passed by value instead of reference:

https://github.com/devernay/cminpack/blob/master/cminpackP.h#L18

### CODE REVIEW

**Comment by devernay** [comment]
Can you please elaborate? As documented, this flag is for using cblas, which has C calling conventions, and function names not ending with an underscore. Integers are passed by value in cblas.
Which version of cblas are you using?

**Comment by devernay** [comment]
Oh I see now... We switched from cblas to blas 3 years ago, but the function signatures were not changed. Can you please make a PR to update cminpackP.h instead?

**Comment by devernay** [comment]
See #53

**Comment by devernay** [comment]
https://github.com/devernay/cminpack/pull/68 tries to really fix the issue. Does that look ok to you?

**Comment by jschueller** [comment]
I got this error with your branch:
```
/cminpack/enorm_.c:59:11: error: unknown type name ‘__cminpack_blasint__’
   59 |     const __cminpack_blasint__ c__1 = 1;
```
this should probably be tested in the CI

**Comment by devernay** [comment]
Yes, it's still a draft

**Comment by devernay** [comment]
updated #68

**Comment by jschueller** [comment]
ok, it builds now

**Comment by jschueller** [comment]
configuration fails if blas is unavailable (ie windows) or if extended precision is enabled (by default)
should we still disable blas by default, or use it only if available and only for non extended precision variants ?

**Comment by devernay** [comment]
I think BLAS support should be disabled by default, because results may depend on the BLAS implementation, and this may lead to unexpected results, depending on which BLAS is installed.

**Comment by chenrui333** [comment]
> I think BLAS support should be disabled by default, because results may depend on the BLAS implementation, and this may lead to unexpected results, depending on which BLAS is installed.

is openblas supported, if so, can we maybe add it to the CI? 

relates to https://github.com/Homebrew/homebrew-core/pull/183713

**Pull request closed without merging**
