### PR TITLE
fix BLAS usage (broken by #53)

### PR DESCRIPTION
**Pull request by devernay**
As pointed out by @jschueller in #66, PR #53 broke the BLAS support by not passing all arguments as references.

### CODE REVIEW

**Comment by devernay** [comment]
Compiles, but tests don't pass, see https://github.com/devernay/cminpack/actions/runs/9693835725/job/26750173978?pr=68

failure example:
```
--- examples/ref/tlmder1c.ref	2024-05-28 22:47:05
+++ examples/tlmder1c.out	2024-06-27 11:06:38
@@ -1,7 +1,7 @@
-      final l2 norm of the residuals     0.09063596
+      final l2 norm of the residuals             15

-      exit parameter                         1
+      exit parameter                         2

       final approximate solution

-          0.08241058       1.133037       2.343695
+                   1              1              1
```

**Comment by jschueller** [comment]
tests pass on my end

**Comment by anntzer** [comment]
I no longer regularly use cminpack and am furthermore unable to review this in the coming month or so due to other priorities, so feel free to push this forward without me.  I'll keep a note to look at this if this is still open once I'm available again, though.

**Comment by devernay** [comment]
tlmdifc failed because of FP precision. disabled it

**Comment by jschueller** [comment]
do you plan a new patch release ?

**Comment by devernay** [comment]
Once we settle wether  https://github.com/devernay/cminpack/pull/64 can be merged. Can you review it please?

**Comment by jschueller** [comment]
yes, its not so great atm

**Comment by jschueller** [comment]
@devernay would it be possible to release a new version so that the fixes for using blas are included ?
it would avoid to use the broken 1.3.9 version with blas enabled like homebrew does

**Comment by devernay** [comment]
> @devernay would it be possible to release a new version so that the fixes for using blas are included ? it would avoid downstream to use the broken 1.3.9 version when blas is enabled like homebrew does

done!

**Pull request merged**
