### PR TITLE
Dont use cmake LOCATION property

### PR DESCRIPTION
**Pull request by xantares**

### CODE REVIEW

**Comment by xantares** [comment]
This one is deprecated and a emits lots of warnings

**Comment by devernay** [comment]
seems legit. Can someone else (I'm no cmake expert) confirm it's ok?

**Comment by xantares** [comment]
The log shows:
```
Call Stack (most recent call first):
  examples/CMakeLists.txt:37 (add_minpack_test)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at examples/CMakeLists.txt:22 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "tfdjac2c".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

```

see https://cmake.org/cmake/help/latest/prop_tgt/LOCATION.html?highlight=location

**Comment by xantares** [comment]
@devernay is it ok to merge ?

**Comment by devernay** [comment]
This breaks the build, see https://ci.appveyor.com/project/devernay/cminpack/builds/22314483

**Comment by devernay** [comment]
reverting for now. can you please provide a fix that works on windows/appveyor too?

**Pull request merged**
