### PR TITLE
CMake: Fix pkgconfig files

### PR DESCRIPTION
**Pull request by jschueller**
I propose this simpler fixes instead of #64:
- fixes library suffix
- adds missing -D__cminpack_xxx__ define
- USE_BLAS macro is private
- also fixes examples: genf77tests rule, check d target and drop unneeded libm link

/cc @luau-project

### CODE REVIEW

**Comment by luau-project** [comment]
Hello.

I liked the idea that you used to solve the library suffix. However, there is something not working correctly.

For instance, run this shell script on your branch on a Debian-derived distro (I used Ubuntu 24.04):

```sh
cd /tmp
rm -rf cminpack
git clone --branch=pkgconfig https://github.com/jschueller/cminpack
cmake -DUSE_BLAS=OFF -DBUILD_SHARED_LIBS=ON --install-prefix $PWD/install -S cminpack/ -B _build
cmake --build _build/
ctest --test-dir _build/
cmake --install _build/
cat /tmp/install/lib/pkgconfig/cminpack.pc
```

You get the following screen:

Screenshot from 2024-06-28 11-50-40

In the end of the image, you can see the ```-D__cminpack_float__``` for the double-precision version ```cminpack.pc```.

**Comment by jschueller** [comment]
indeed, PC_CMINPACK_CFLAGS must be reset, fixed now

**Comment by luau-project** [comment]
## Comments

On the tests I ran after your fixed ```PC_CMINPACK_CFLAGS```, I didn't find any issues related to the generated pkgconfig files, nor the CMinpackConfig scripts.

I think your PR has a cleaner solution to fix pkgconfig files while keeping compatibility to previous versions. If the main intent is to fix pkgconfig related things, I think your PR is ready to be merged.

## Extra (could be addressed on subsequent PRs or newer commits)

In my PR, I also added a guard to only test the library if the double-precision version was built. Because you can see here [https://github.com/jschueller/cminpack/blob/pkgconfig/examples/CMakeLists.txt#L33](https://github.com/jschueller/cminpack/blob/pkgconfig/examples/CMakeLists.txt#L33) and here [https://github.com/jschueller/cminpack/blob/pkgconfig/examples/CMakeLists.txt#L65](https://github.com/jschueller/cminpack/blob/pkgconfig/examples/CMakeLists.txt#L65), it is testing only for the double precision version.

**Comment by jschueller** [comment]
done too

**Comment by luau-project** [comment]
I didn't test, but I guess the same target guard is needed here [https://github.com/jschueller/cminpack/blob/pkgconfig/examples/CMakeLists.txt#L47](https://github.com/jschueller/cminpack/blob/pkgconfig/examples/CMakeLists.txt#L47)

**Comment by jschueller** [comment]
indeeed

**Comment by luau-project** [comment]
In my view, I think your PR is now ready to be merged.

**Comment by devernay** [comment]
Why don't we get full CI build on this PR? The whole ubuntu matrix is missing

**Comment by jschueller** [comment]
github is having troubles: https://www.githubstatus.com/

**Pull request merged**
