### PR TITLE
File reorganization, and doxygen configuration

### PR DESCRIPTION
**Pull request by fake-name**
This is basically a giant "move things about" PR. 

Principally, the current source files are now in `./src`, and the legacy versions are in `./legacy_minpack`. 

I've patched the makefiles for the move, and as many of the tests pass now as they did before the move (I think I'm missing some cuda dependencies, or something).

Additionally, I've added both a `Doxyfile` and doxygen module declarations to the different code files, so from the `doxygen` folder, running `doxygen`  will produce some automatic HTML documentation. 

Stuff still to do:

 - Doxygen doesn't understand the comments layout in the various files, so you get function signatures and not much else at this point. 
 - I think the cmake build is somewhat broken. 
 - There's still a horrible mess of tabs/spaces indentation I meant to make coherent.

### CODE REVIEW

**Comment by fake-name** [comment]
With proper doxygen comments, you get something like:


untitled

Automatically generated.

**Comment by devernay** [comment]
sorry, I'm against moving things over and reindenting everything: this messes up the history of changes.
C/C++ minpack works very well as it is and is used by many.
It is included in many distributions as well. The only "legacy" files are the FORTRAN ones, evrerything else is maintained and works well. This is rock-solid software and is not going to change much.
As I said before, feel free to clarify the documentation for the software.

**Comment by fake-name** [comment]
At least cherry-pick the doxygen commit, and maybe the one that fixes the mixed tab/space indentation. 

Doxygen is /great/. You should use it.

**Comment by devernay** [comment]
The real documentation for minpack is in a text file and a few scanned PDFs. Doxygen is totally useless in this case. And yes, I know doxygen, as I have been contributing to open source software for more than twenty years.

**Pull request closed without merging**
