### PR TITLE
fix: EOL problems running CMake tests on Windows

### PR DESCRIPTION
**Pull request by luau-project**
## Description

I have improved cminpack build with CMake on Windows. In the actual behavior when building with CMake, in order for the tests to pass, you have to two ways:
1. enforce ```git config --global core.autocrlf true``` before checking out the source code from github;
2. download the released tarball and convert manually LF (\n) to CRLF (\r\n) all the reference test files (*.ref) found at ```examples/ref/```

In the new behavior, there is no need to perform LF to CRLF conversion anymore.

## How

* I added an argument ```--enable-eol``` on file [examples/runtest.cmake](examples/runtest.cmake) to discard any EOL differences;
* In order to use the argument ```--enable-eol``` mentioned above, according to [https://cmake.org/cmake/help/latest/manual/cmake.1.html](https://cmake.org/cmake/help/latest/manual/cmake.1.html), CMake needs to be on version 3.14 or newer. So, I bumped the minimum CMake version to 3.14 on file [CMakeLists.txt](CMakeLists.txt).

## Tests

To verify that my proposed changes were correct, I discarded  the entries ```git config --global core.autocrlf true``` in the builds at CI services, which can be found at [.github/workflows/windows-visual-studio-cminpack-install.yaml](.github/workflows/windows-visual-studio-cminpack-install.yaml) and [appveyor.yml](appveyor.yml).

## Bonus

I simplified the build on AppVeyor CI [appveyor.yml](appveyor.yml).

### CODE REVIEW

**Review by devernay — APPROVED** [review]

**Review by devernay — APPROVED** [review]

**Review by devernay — APPROVED** [review]

**Comment by luau-project** [comment]
## Update

On my branch, I was able to port MSYS2 CI to github. Github is much faster, because jobs run in parallel.

**Comment by luau-project** [comment]
## Update

@devernay 

In the current state, which I consider to be ready to merge, I removed the AppVeyor CI integration (deleted ```appveyor.yml```) in favor of Github CI, because it is faster.

Rest assured that CI is now better, which you can check on my branch [https://github.com/luau-project/cminpack/tree/fix-cmake-eol-on-tests](https://github.com/luau-project/cminpack/tree/fix-cmake-eol-on-tests) Github actions (building correctly 49 different tests), including 24 tests with MSYS2 toolchains.

> [!IMPORTANT]
> 
> In order to cancel AppVeyor CI, you have to log in on your account there, and delete the cminpack project on the project settings, otherwise it will continue to fail on each push.

**Comment by luau-project** [comment]
## Update

Merged master, and restored back AppVeyor file for the checks to pass here.

> [!IMPORTANT]
> 
> However, it is still highly recommended to turn off the AppVeyor CI removing the project on their website, because:
> * Github workflows is already setup for MSYS2 and MSVC
> * AppVeyor runs slower than Github, because Github jobs run in parallel
> * AppVeyor can fail (false-positive) while downloading packages or updates from MSYS2 due a great load on MSYS2 servers.

**Comment by devernay** [comment]
LGTM!

**Pull request merged**
